### PR TITLE
Support hpack files

### PR DESCRIPTION
**Pull request by sergv**
A fix for #85.

### CODE REVIEW

**Comment by sergv** [comment]
@jbaum98 Could you please give this branch a try and see whether it handles your hpack configuration well?

**Comment by jbaum98** [comment]
I've given it a try, and it works sort of! It seems to be working, but it also gives me an error message
```
get-cabal-configuration.hs: dieVerbatim: user error (get-cabal-configuration.hs: Error Parsing: file "~/dependent-haskell/" doesn't exist. Cannot continue.
```
where the `~/dependent-haskell` is the source directory for the haskell project.

**Comment by sergv** [comment]
@jbaum98 Sorry about that, I believe it's fixed now. Can you give it another spin, please?

**Comment by jbaum98** [comment]
Works great! The one thing is it doesn't recognize seems to be `ghc-options`, but it does get everything else. Thanks!

**Comment by sergv** [comment]
There's a list of allowed `ghc-options` https://github.com/flycheck/flycheck-haskell/blob/master/get-cabal-configuration.hs#L209-L232, so maybe you tried to specify an unsupported one.

**Comment by sergv** [comment]
I'll merge the branch now. If you belive the issue with `ghc-options` persists then please create a new issue and provide a reproducible example.

**Comment by jbaum98** [comment]
I see! No it isn't on the list. Why are the options filtered? For example, this option disables a certain warning, shouldn't that be allowed?

**Comment by sergv** [comment]
Well, some flags are meaningless for a checker like flycheck. For example, there are flags that dump information from compiler, like [-ddump-deriv](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/debugging.html#ghc-flag--ddump-deriv), which by default print something to standard output. It's not likely that user would want to see that since flycheck's job is to just check whether a file compiles. There are flags to redirect that output to a file (`-ddump-to-file`), but still flycheck probably shouldn't trigger regeneration of that file every time e.g. an emacs buffer is saved.

I am not avare of the original motivation, but my guess would be that flycheck-haskell wants to be future-proof: if in the future ghc will add some strange flag, we won't inadvertedly use it and cause havoc. If the flag turns out to be essential then  we'll add support for it.

PS Actually options controlling warnings are covered since they're going to start with either `-fwarn-` or `-fno-warn`, respectively, which are listed under allowed prefixes.

**Comment by jbaum98** [comment]
[It seems like](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#warnings-and-sanity-checking) there are other options affecting warnings that begin with `-W`. Should I make a issue/pull request adding `-W` to the allowed option prefixes?

**Comment by sergv** [comment]
Yes, that's a great idea. Please do open a PR.

On 21 March 2018 03:26:51 GMT+00:00, Jake Waksbaum <notifications@github.com> wrote:
>[It seems
>like](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#warnings-and-sanity-checking)
>there are other options affecting warnings that begin with `-W`. Should
>I make a issue/pull request adding `-W` to the allowed option prefixes?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/flycheck/flycheck-haskell/pull/86#issuecomment-374824802

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
